package com.greenspacevoid.client.ui.menus.ui.auxiliary.social;

import com.intellij.uiDesigner.core.GridConstraints;
import com.intellij.uiDesigner.core.GridLayoutManager;

import javax.swing.*;
import java.awt.*;
import java.util.ArrayList;

public class ChatMenu {

    //Todo: Create a custom chat window that can be duplicated/delegated into numerous tabbed JPanels


    private JPanel chatMenuPanel;
    private JTabbedPane tabbedPane1;
    private JPanel localChannelPanel;
    private JTextArea chatTextArea;
    private JList userInChannelList;
    private JScrollPane chatWindowScrollpane;
    private JLabel channelDescriptionLabel;
    private JLabel usersInChannelLabel;
    private JTextField messageTextField;
    private JButton sendButton;
    private JScrollPane userListScrollpane;






    public void addChatRoom(/*Mystery data in here B) */){

        //Todo: On connect, add the player's personal chat rooms to their client. B)




    }

    public void updateChat(String channelID, String message, String username){

        //Specify channel, message, and sender B) Listener on the client listens for enter keystrokes to send a message.







    }








    {
// GUI initializer generated by IntelliJ IDEA GUI Designer
// >>> IMPORTANT!! <<<
// DO NOT EDIT OR ADD ANY CODE HERE!
        $$$setupUI$$$();
    }

    /**
     * Method generated by IntelliJ IDEA GUI Designer
     * >>> IMPORTANT!! <<<
     * DO NOT edit this method OR call it in your code!
     *
     * @noinspection ALL
     */
    private void $$$setupUI$$$() {
        chatMenuPanel = new JPanel();
        chatMenuPanel.setLayout(new GridLayoutManager(1, 1, new Insets(0, 0, 0, 0), -1, -1));
        tabbedPane1 = new JTabbedPane();
        chatMenuPanel.add(tabbedPane1, new GridConstraints(0, 0, 1, 1, GridConstraints.ANCHOR_CENTER, GridConstraints.FILL_BOTH, GridConstraints.SIZEPOLICY_CAN_SHRINK | GridConstraints.SIZEPOLICY_CAN_GROW, GridConstraints.SIZEPOLICY_CAN_SHRINK | GridConstraints.SIZEPOLICY_CAN_GROW, null, new Dimension(200, 200), null, 0, false));
        localChannelPanel = new JPanel();
        localChannelPanel.setLayout(new GridLayoutManager(1, 1, new Insets(0, 0, 0, 0), -1, -1));
        tabbedPane1.addTab("Local", localChannelPanel);
    }

    /**
     * @noinspection ALL
     */
    public JComponent $$$getRootComponent$$$() {
        return chatMenuPanel;
    }
}
