package com.greenspacevoidUI.menus.auxiliary.economy;

import com.intellij.uiDesigner.core.GridConstraints;
import com.intellij.uiDesigner.core.GridLayoutManager;

import javax.swing.*;
import javax.swing.border.TitledBorder;
import java.awt.*;

public class AssetsMenu {
    private JTabbedPane assetsMenuTabbedPane;
    private JPanel assetsMenuPanel;
    private JPanel assetsPanel;
    private JTable assetsTable;
    private JTree locationsTree;
    private JLabel totalAssetWorthLabel;
    private JLabel individualAssetWorthLabel;
    private JScrollPane locationsScrollPane;
    private JScrollPane assetsScrollpane;

    {
// GUI initializer generated by IntelliJ IDEA GUI Designer
// >>> IMPORTANT!! <<<
// DO NOT EDIT OR ADD ANY CODE HERE!
        $$$setupUI$$$();
    }

    /**
     * Method generated by IntelliJ IDEA GUI Designer
     * >>> IMPORTANT!! <<<
     * DO NOT edit this method OR call it in your code!
     *
     * @noinspection ALL
     */
    private void $$$setupUI$$$() {
        assetsMenuPanel = new JPanel();
        assetsMenuPanel.setLayout(new GridLayoutManager(1, 1, new Insets(0, 0, 0, 0), -1, -1));
        assetsMenuPanel.setBorder(BorderFactory.createTitledBorder(BorderFactory.createEtchedBorder(), "Personal Assets", TitledBorder.CENTER, TitledBorder.DEFAULT_POSITION, null, null));
        assetsMenuTabbedPane = new JTabbedPane();
        assetsMenuPanel.add(assetsMenuTabbedPane, new GridConstraints(0, 0, 1, 1, GridConstraints.ANCHOR_CENTER, GridConstraints.FILL_BOTH, GridConstraints.SIZEPOLICY_CAN_SHRINK | GridConstraints.SIZEPOLICY_CAN_GROW, GridConstraints.SIZEPOLICY_CAN_SHRINK | GridConstraints.SIZEPOLICY_CAN_GROW, null, new Dimension(200, 200), null, 0, false));
        assetsPanel = new JPanel();
        assetsPanel.setLayout(new GridLayoutManager(3, 2, new Insets(0, 0, 0, 0), -1, -1));
        assetsMenuTabbedPane.addTab("Assets", assetsPanel);
        final JLabel label1 = new JLabel();
        label1.setText("Locations:");
        assetsPanel.add(label1, new GridConstraints(0, 0, 1, 1, GridConstraints.ANCHOR_WEST, GridConstraints.FILL_NONE, GridConstraints.SIZEPOLICY_FIXED, GridConstraints.SIZEPOLICY_FIXED, null, null, null, 0, false));
        final JLabel label2 = new JLabel();
        label2.setText("Contents:");
        assetsPanel.add(label2, new GridConstraints(0, 1, 1, 1, GridConstraints.ANCHOR_WEST, GridConstraints.FILL_NONE, GridConstraints.SIZEPOLICY_FIXED, GridConstraints.SIZEPOLICY_FIXED, null, null, null, 0, false));
        totalAssetWorthLabel = new JLabel();
        totalAssetWorthLabel.setText("Total Asset Est. Worth: $1,234,567");
        assetsPanel.add(totalAssetWorthLabel, new GridConstraints(2, 0, 1, 1, GridConstraints.ANCHOR_WEST, GridConstraints.FILL_NONE, GridConstraints.SIZEPOLICY_FIXED, GridConstraints.SIZEPOLICY_FIXED, null, null, null, 0, false));
        individualAssetWorthLabel = new JLabel();
        individualAssetWorthLabel.setText("Est. Value $1,234,567");
        assetsPanel.add(individualAssetWorthLabel, new GridConstraints(2, 1, 1, 1, GridConstraints.ANCHOR_WEST, GridConstraints.FILL_NONE, GridConstraints.SIZEPOLICY_FIXED, GridConstraints.SIZEPOLICY_FIXED, null, null, null, 0, false));
        locationsScrollPane = new JScrollPane();
        assetsPanel.add(locationsScrollPane, new GridConstraints(1, 0, 1, 1, GridConstraints.ANCHOR_CENTER, GridConstraints.FILL_BOTH, GridConstraints.SIZEPOLICY_CAN_SHRINK | GridConstraints.SIZEPOLICY_WANT_GROW, GridConstraints.SIZEPOLICY_CAN_SHRINK | GridConstraints.SIZEPOLICY_WANT_GROW, null, null, null, 0, false));
        locationsTree = new JTree();
        locationsScrollPane.setViewportView(locationsTree);
        assetsScrollpane = new JScrollPane();
        assetsPanel.add(assetsScrollpane, new GridConstraints(1, 1, 1, 1, GridConstraints.ANCHOR_CENTER, GridConstraints.FILL_BOTH, GridConstraints.SIZEPOLICY_CAN_SHRINK | GridConstraints.SIZEPOLICY_WANT_GROW, GridConstraints.SIZEPOLICY_CAN_SHRINK | GridConstraints.SIZEPOLICY_WANT_GROW, null, null, null, 0, false));
        assetsTable = new JTable();
        assetsScrollpane.setViewportView(assetsTable);
    }

    /**
     * @noinspection ALL
     */
    public JComponent $$$getRootComponent$$$() {
        return assetsMenuPanel;
    }

    //Right click functionality allows for destination setting, item information,sale (if possible) and what have you


}
