package com.greenspacevoid.client.ui.menus.ui.auxiliary.inventory;

import com.intellij.uiDesigner.core.GridLayoutManager;

import javax.swing.*;
import java.awt.*;

public class ItemInformation {
    private JTabbedPane itemInformationTabbedPane;
    private JPanel itemPanel;
    private JTextArea descriptionUngaYouCanTextArea;
    private JTree requiredSkillTree;
    private JTable statisticsTable;
    private JScrollPane statisticsScrollPane;
    private JPanel requiredSkillsScrollPane;
    private JScrollPane infoScrollPane;
    private JPanel industryPanel;
    private JTable requiredMaterialsTable;
    private JScrollPane requiredMaterialsScrollPane;
    private JLabel buildTimeLabel;

    {
// GUI initializer generated by IntelliJ IDEA GUI Designer
// >>> IMPORTANT!! <<<
// DO NOT EDIT OR ADD ANY CODE HERE!
        $$$setupUI$$$();
    }

    /**
     * Method generated by IntelliJ IDEA GUI Designer
     * >>> IMPORTANT!! <<<
     * DO NOT edit this method OR call it in your code!
     *
     * @noinspection ALL
     */
    private void $$$setupUI$$$() {
        final JPanel panel1 = new JPanel();
        panel1.setLayout(new GridLayoutManager(1, 1, new Insets(0, 0, 0, 0), -1, -1));
    }
}
