package com.greenspacevoid.client.ui.menus.ui.auxiliary.industry;

import com.intellij.uiDesigner.core.GridLayoutManager;

import javax.swing.*;
import java.awt.*;

public class ShipyardIndustryMenu {
    private JTabbedPane shipyardTabbedPane;
    private JPanel shipyardPanel;
    private JTable componentHoldTable;
    private JScrollPane componentHoldTableScrollpane;
    private JPanel storagePane;
    private JComboBox classSelect;
    private JComboBox modelSelect;
    private JLabel estimatedHoldValueLabel;
    private JPanel overviewPanel;
    private JPanel buildMenuPanel;
    private JComboBox factionSelect;
    private JTextArea textArea1;
    private JButton buildButton;
    private JProgressBar progressBar1;
    private JComboBox comboBox1;
    private JPanel constructionInfoTextArea;
    private JProgressBar progressBar2;
    private JTextArea shipyardInfoTextArea;
    private JLabel currentTaskLabel;

    {
// GUI initializer generated by IntelliJ IDEA GUI Designer
// >>> IMPORTANT!! <<<
// DO NOT EDIT OR ADD ANY CODE HERE!
        $$$setupUI$$$();
    }

    /**
     * Method generated by IntelliJ IDEA GUI Designer
     * >>> IMPORTANT!! <<<
     * DO NOT edit this method OR call it in your code!
     *
     * @noinspection ALL
     */
    private void $$$setupUI$$$() {
        final JPanel panel1 = new JPanel();
        panel1.setLayout(new GridLayoutManager(1, 1, new Insets(0, 0, 0, 0), -1, -1));
    }
}
