package com.greenspacevoid.client.ui.menus.ui.auxiliary.economy;

import com.intellij.uiDesigner.core.GridConstraints;
import com.intellij.uiDesigner.core.GridLayoutManager;

import javax.swing.*;
import javax.swing.border.TitledBorder;
import java.awt.*;

public class MarketMenu {

    //User created
    private JScrollPane scrollbar;

    private JPanel marketPanel;
    private JTabbedPane tabbedPane1;
    private JPanel buyPanel;
    private JTree itemBrowserTree;
    private JTable sellOrdersTable;
    private JTable buyOrderstTable;
    private JScrollPane browserScrollPane;
    private JTextField itemSearchBar;
    private JButton openWalletButton;
    private JButton createBuyOrderButton;
    private JTextPane itemInfoPane;
    private JTable priceHistoryTable;
    private JPanel priceHistoryPanel;
    private JLabel currentBalanceLabel;
    private JButton viewDetailsButton;
    private JScrollPane buyOrdersScrollPane;
    private JScrollPane sellOrdersScrollPane;
    private JScrollPane priceHistoryScrollPane;
    private JComboBox comboBox1;


    public static void createMarketMenu() {
        JFrame frame = new JFrame("MarketMenu");

        MarketMenu menu = new MarketMenu();

        frame.setContentPane(menu.marketPanel);
        frame.setDefaultCloseOperation(JFrame.EXIT_ON_CLOSE);

        frame.pack();
        frame.setVisible(true);


    }


    private void createUIComponents() {
        // TODO: place custom component creation code here
        scrollbar = new JScrollPane(itemBrowserTree);
    }

    {
// GUI initializer generated by IntelliJ IDEA GUI Designer
// >>> IMPORTANT!! <<<
// DO NOT EDIT OR ADD ANY CODE HERE!
        $$$setupUI$$$();
    }

    /**
     * Method generated by IntelliJ IDEA GUI Designer
     * >>> IMPORTANT!! <<<
     * DO NOT edit this method OR call it in your code!
     *
     * @noinspection ALL
     */
    private void $$$setupUI$$$() {
        marketPanel = new JPanel();
        marketPanel.setLayout(new GridLayoutManager(4, 7, new Insets(0, 0, 0, 0), -1, -1));
        marketPanel.setBorder(BorderFactory.createTitledBorder(BorderFactory.createEtchedBorder(), "Market", TitledBorder.DEFAULT_JUSTIFICATION, TitledBorder.DEFAULT_POSITION, null, null));
        tabbedPane1 = new JTabbedPane();
        marketPanel.add(tabbedPane1, new GridConstraints(2, 3, 1, 4, GridConstraints.ANCHOR_CENTER, GridConstraints.FILL_BOTH, GridConstraints.SIZEPOLICY_CAN_SHRINK | GridConstraints.SIZEPOLICY_CAN_GROW, GridConstraints.SIZEPOLICY_CAN_SHRINK | GridConstraints.SIZEPOLICY_CAN_GROW, null, new Dimension(200, 200), null, 0, false));
        buyPanel = new JPanel();
        buyPanel.setLayout(new GridLayoutManager(4, 3, new Insets(0, 0, 0, 0), -1, -1));
        tabbedPane1.addTab("Market Orders", buyPanel);
        final JLabel label1 = new JLabel();
        label1.setText("Buy Orders:");
        buyPanel.add(label1, new GridConstraints(2, 0, 1, 1, GridConstraints.ANCHOR_WEST, GridConstraints.FILL_NONE, GridConstraints.SIZEPOLICY_FIXED, GridConstraints.SIZEPOLICY_FIXED, null, null, null, 0, false));
        final JLabel label2 = new JLabel();
        label2.setText("Sell Orders:");
        buyPanel.add(label2, new GridConstraints(0, 0, 1, 3, GridConstraints.ANCHOR_WEST, GridConstraints.FILL_NONE, GridConstraints.SIZEPOLICY_FIXED, GridConstraints.SIZEPOLICY_FIXED, null, null, null, 0, false));
        sellOrdersScrollPane = new JScrollPane();
        sellOrdersScrollPane.setVerticalScrollBarPolicy(22);
        buyPanel.add(sellOrdersScrollPane, new GridConstraints(1, 0, 1, 3, GridConstraints.ANCHOR_CENTER, GridConstraints.FILL_BOTH, GridConstraints.SIZEPOLICY_CAN_SHRINK | GridConstraints.SIZEPOLICY_WANT_GROW, GridConstraints.SIZEPOLICY_CAN_SHRINK | GridConstraints.SIZEPOLICY_WANT_GROW, null, null, null, 0, false));
        sellOrdersTable = new JTable();
        sellOrdersScrollPane.setViewportView(sellOrdersTable);
        buyOrdersScrollPane = new JScrollPane();
        buyOrdersScrollPane.setVerticalScrollBarPolicy(22);
        buyPanel.add(buyOrdersScrollPane, new GridConstraints(3, 0, 1, 3, GridConstraints.ANCHOR_CENTER, GridConstraints.FILL_BOTH, GridConstraints.SIZEPOLICY_CAN_SHRINK | GridConstraints.SIZEPOLICY_WANT_GROW, GridConstraints.SIZEPOLICY_CAN_SHRINK | GridConstraints.SIZEPOLICY_WANT_GROW, null, null, null, 0, false));
        buyOrderstTable = new JTable();
        buyOrdersScrollPane.setViewportView(buyOrderstTable);
        priceHistoryPanel = new JPanel();
        priceHistoryPanel.setLayout(new GridLayoutManager(2, 2, new Insets(0, 0, 0, 0), -1, -1));
        tabbedPane1.addTab("Price History", priceHistoryPanel);
        priceHistoryScrollPane = new JScrollPane();
        priceHistoryScrollPane.setVerticalScrollBarPolicy(22);
        priceHistoryPanel.add(priceHistoryScrollPane, new GridConstraints(1, 0, 1, 2, GridConstraints.ANCHOR_CENTER, GridConstraints.FILL_BOTH, GridConstraints.SIZEPOLICY_CAN_SHRINK | GridConstraints.SIZEPOLICY_WANT_GROW, GridConstraints.SIZEPOLICY_CAN_SHRINK | GridConstraints.SIZEPOLICY_WANT_GROW, null, null, null, 0, false));
        priceHistoryTable = new JTable();
        priceHistoryScrollPane.setViewportView(priceHistoryTable);
        comboBox1 = new JComboBox();
        priceHistoryPanel.add(comboBox1, new GridConstraints(0, 0, 1, 1, GridConstraints.ANCHOR_WEST, GridConstraints.FILL_HORIZONTAL, GridConstraints.SIZEPOLICY_CAN_GROW, GridConstraints.SIZEPOLICY_FIXED, null, null, null, 0, false));
        browserScrollPane = new JScrollPane();
        browserScrollPane.setHorizontalScrollBarPolicy(31);
        browserScrollPane.setVerticalScrollBarPolicy(21);
        marketPanel.add(browserScrollPane, new GridConstraints(2, 0, 1, 3, GridConstraints.ANCHOR_CENTER, GridConstraints.FILL_BOTH, GridConstraints.SIZEPOLICY_FIXED, GridConstraints.SIZEPOLICY_CAN_SHRINK | GridConstraints.SIZEPOLICY_WANT_GROW, null, null, null, 0, false));
        itemBrowserTree = new JTree();
        browserScrollPane.setViewportView(itemBrowserTree);
        openWalletButton = new JButton();
        openWalletButton.setText("Open Wallet");
        marketPanel.add(openWalletButton, new GridConstraints(3, 3, 1, 1, GridConstraints.ANCHOR_CENTER, GridConstraints.FILL_HORIZONTAL, GridConstraints.SIZEPOLICY_CAN_SHRINK | GridConstraints.SIZEPOLICY_CAN_GROW, GridConstraints.SIZEPOLICY_FIXED, null, null, null, 0, false));
        createBuyOrderButton = new JButton();
        createBuyOrderButton.setText("Create Buy Order");
        marketPanel.add(createBuyOrderButton, new GridConstraints(3, 5, 1, 2, GridConstraints.ANCHOR_CENTER, GridConstraints.FILL_HORIZONTAL, GridConstraints.SIZEPOLICY_CAN_SHRINK | GridConstraints.SIZEPOLICY_CAN_GROW, GridConstraints.SIZEPOLICY_FIXED, null, null, null, 0, false));
        viewDetailsButton = new JButton();
        viewDetailsButton.setText("View Details");
        marketPanel.add(viewDetailsButton, new GridConstraints(3, 4, 1, 1, GridConstraints.ANCHOR_CENTER, GridConstraints.FILL_HORIZONTAL, GridConstraints.SIZEPOLICY_CAN_SHRINK | GridConstraints.SIZEPOLICY_CAN_GROW, GridConstraints.SIZEPOLICY_FIXED, null, null, null, 0, false));
        itemSearchBar = new JTextField();
        itemSearchBar.setName("Search");
        itemSearchBar.setText("");
        marketPanel.add(itemSearchBar, new GridConstraints(1, 0, 1, 3, GridConstraints.ANCHOR_WEST, GridConstraints.FILL_HORIZONTAL, GridConstraints.SIZEPOLICY_FIXED, GridConstraints.SIZEPOLICY_FIXED, null, new Dimension(150, -1), null, 0, false));
        final JLabel label3 = new JLabel();
        label3.setText("Search:");
        marketPanel.add(label3, new GridConstraints(0, 0, 1, 1, GridConstraints.ANCHOR_WEST, GridConstraints.FILL_NONE, GridConstraints.SIZEPOLICY_FIXED, GridConstraints.SIZEPOLICY_FIXED, null, null, null, 0, false));
        itemInfoPane = new JTextPane();
        itemInfoPane.setEditable(false);
        marketPanel.add(itemInfoPane, new GridConstraints(0, 3, 2, 4, GridConstraints.ANCHOR_CENTER, GridConstraints.FILL_BOTH, GridConstraints.SIZEPOLICY_WANT_GROW, GridConstraints.SIZEPOLICY_WANT_GROW, null, new Dimension(150, 50), null, 0, false));
        final JLabel label4 = new JLabel();
        label4.setText("Info:");
        marketPanel.add(label4, new GridConstraints(0, 2, 1, 1, GridConstraints.ANCHOR_EAST, GridConstraints.FILL_NONE, GridConstraints.SIZEPOLICY_FIXED, GridConstraints.SIZEPOLICY_FIXED, null, null, null, 0, false));
        currentBalanceLabel = new JLabel();
        currentBalanceLabel.setText("Balance: $1,234,567");
        marketPanel.add(currentBalanceLabel, new GridConstraints(3, 0, 1, 3, GridConstraints.ANCHOR_WEST, GridConstraints.FILL_NONE, GridConstraints.SIZEPOLICY_FIXED, GridConstraints.SIZEPOLICY_FIXED, null, null, null, 0, false));
    }

    /**
     * @noinspection ALL
     */
    public JComponent $$$getRootComponent$$$() {
        return marketPanel;
    }


}
