package com.greenspacevoid.client.ui.menus.ui.auxiliary.economy;

import com.intellij.uiDesigner.core.GridConstraints;
import com.intellij.uiDesigner.core.GridLayoutManager;
import com.intellij.uiDesigner.core.Spacer;

import javax.swing.*;
import java.awt.*;

public class TransactionsMenu {
    private JTabbedPane tabbedPane1;
    private JPanel masterPanel;
    private JPanel transactionsPanel;
    private JTable transactionTable;
    private JScrollPane transactionPanelScrollPane;
    private JPanel financeReportPanel;
    private JSlider profitMarginDisplay;
    private JLabel proftMarginLabel;
    private JComboBox timeScaleSelectionBox;
    private JTextPane currentBalance$1234TextPane;
    private JLabel statisticOverPastAmountOfTimeLabel;
    private JLabel defecitLabel;
    private JLabel netIncomeLabel;
    private JTextPane transactionsInfoPane;

    {
// GUI initializer generated by IntelliJ IDEA GUI Designer
// >>> IMPORTANT!! <<<
// DO NOT EDIT OR ADD ANY CODE HERE!
        $$$setupUI$$$();
    }

    /**
     * Method generated by IntelliJ IDEA GUI Designer
     * >>> IMPORTANT!! <<<
     * DO NOT edit this method OR call it in your code!
     *
     * @noinspection ALL
     */
    private void $$$setupUI$$$() {
        masterPanel = new JPanel();
        masterPanel.setLayout(new GridLayoutManager(1, 1, new Insets(0, 0, 0, 0), -1, -1));
        tabbedPane1 = new JTabbedPane();
        masterPanel.add(tabbedPane1, new GridConstraints(0, 0, 1, 1, GridConstraints.ANCHOR_CENTER, GridConstraints.FILL_BOTH, GridConstraints.SIZEPOLICY_CAN_SHRINK | GridConstraints.SIZEPOLICY_CAN_GROW, GridConstraints.SIZEPOLICY_CAN_SHRINK | GridConstraints.SIZEPOLICY_CAN_GROW, null, new Dimension(200, 200), null, 0, false));
        financeReportPanel = new JPanel();
        financeReportPanel.setLayout(new GridLayoutManager(6, 2, new Insets(0, 0, 0, 0), -1, -1));
        tabbedPane1.addTab("Finance Report", financeReportPanel);
        profitMarginDisplay = new JSlider();
        profitMarginDisplay.setEnabled(false);
        profitMarginDisplay.setFocusable(false);
        profitMarginDisplay.setMajorTickSpacing(50);
        profitMarginDisplay.setOrientation(1);
        profitMarginDisplay.setPaintLabels(false);
        profitMarginDisplay.setPaintTicks(true);
        profitMarginDisplay.setPaintTrack(false);
        profitMarginDisplay.setValueIsAdjusting(false);
        financeReportPanel.add(profitMarginDisplay, new GridConstraints(4, 0, 1, 1, GridConstraints.ANCHOR_WEST, GridConstraints.FILL_HORIZONTAL, GridConstraints.SIZEPOLICY_FIXED, GridConstraints.SIZEPOLICY_FIXED, null, null, null, 0, false));
        defecitLabel = new JLabel();
        defecitLabel.setForeground(new Color(-65536));
        defecitLabel.setText("Defecit: $1,234,567");
        financeReportPanel.add(defecitLabel, new GridConstraints(5, 0, 1, 1, GridConstraints.ANCHOR_WEST, GridConstraints.FILL_NONE, GridConstraints.SIZEPOLICY_FIXED, GridConstraints.SIZEPOLICY_FIXED, null, null, null, 0, false));
        proftMarginLabel = new JLabel();
        proftMarginLabel.setForeground(new Color(-16711936));
        proftMarginLabel.setText("Profit: $1,234,567");
        financeReportPanel.add(proftMarginLabel, new GridConstraints(1, 0, 3, 1, GridConstraints.ANCHOR_WEST, GridConstraints.FILL_NONE, GridConstraints.SIZEPOLICY_FIXED, GridConstraints.SIZEPOLICY_FIXED, null, null, null, 0, false));
        timeScaleSelectionBox = new JComboBox();
        financeReportPanel.add(timeScaleSelectionBox, new GridConstraints(0, 0, 1, 1, GridConstraints.ANCHOR_WEST, GridConstraints.FILL_HORIZONTAL, GridConstraints.SIZEPOLICY_CAN_GROW, GridConstraints.SIZEPOLICY_FIXED, null, null, null, 0, false));
        statisticOverPastAmountOfTimeLabel = new JLabel();
        statisticOverPastAmountOfTimeLabel.setText("Statistics for the past x amount of time");
        financeReportPanel.add(statisticOverPastAmountOfTimeLabel, new GridConstraints(0, 1, 1, 1, GridConstraints.ANCHOR_WEST, GridConstraints.FILL_NONE, GridConstraints.SIZEPOLICY_FIXED, GridConstraints.SIZEPOLICY_FIXED, null, null, null, 0, false));
        currentBalance$1234TextPane = new JTextPane();
        currentBalance$1234TextPane.setText("Current Balance: $1,234,567\n\nCurrent Income over (past x time): $1,234,567\nCurrent Expenditure over (part x time): $1,234,567\n\nTaxes (Over past x time): $1,234,567\n\nNet Income (over past x time): $1,234,567\n");
        financeReportPanel.add(currentBalance$1234TextPane, new GridConstraints(4, 1, 1, 1, GridConstraints.ANCHOR_CENTER, GridConstraints.FILL_BOTH, GridConstraints.SIZEPOLICY_WANT_GROW, GridConstraints.SIZEPOLICY_WANT_GROW, null, new Dimension(150, 50), null, 0, false));
        netIncomeLabel = new JLabel();
        netIncomeLabel.setText("Net Income: $1,234,567");
        financeReportPanel.add(netIncomeLabel, new GridConstraints(5, 1, 1, 1, GridConstraints.ANCHOR_WEST, GridConstraints.FILL_NONE, GridConstraints.SIZEPOLICY_FIXED, GridConstraints.SIZEPOLICY_FIXED, null, null, null, 0, false));
        transactionsPanel = new JPanel();
        transactionsPanel.setLayout(new GridLayoutManager(2, 1, new Insets(0, 0, 0, 0), -1, -1));
        tabbedPane1.addTab("Transactions", transactionsPanel);
        transactionPanelScrollPane = new JScrollPane();
        transactionPanelScrollPane.setVerticalScrollBarPolicy(22);
        transactionsPanel.add(transactionPanelScrollPane, new GridConstraints(0, 0, 1, 1, GridConstraints.ANCHOR_CENTER, GridConstraints.FILL_BOTH, GridConstraints.SIZEPOLICY_CAN_SHRINK | GridConstraints.SIZEPOLICY_WANT_GROW, GridConstraints.SIZEPOLICY_CAN_SHRINK | GridConstraints.SIZEPOLICY_WANT_GROW, null, null, null, 0, false));
        transactionTable = new JTable();
        transactionPanelScrollPane.setViewportView(transactionTable);
        transactionsInfoPane = new JTextPane();
        transactionsPanel.add(transactionsInfoPane, new GridConstraints(1, 0, 1, 1, GridConstraints.ANCHOR_CENTER, GridConstraints.FILL_BOTH, GridConstraints.SIZEPOLICY_WANT_GROW, GridConstraints.SIZEPOLICY_WANT_GROW, null, new Dimension(150, 50), null, 0, false));
    }

    /**
     * @noinspection ALL
     */
    public JComponent $$$getRootComponent$$$() {
        return masterPanel;
    }

}
